package com.ccpd.forestsun.mapper;

import com.ccpd.forestsun.domain.ItemStock;
import org.apache.ibatis.annotations.Param;

public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Dec 30 00:33:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Dec 30 00:33:55 CST 2018
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Dec 30 00:33:55 CST 2018
     */
    int insertSelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Dec 30 00:33:55 CST 2018
     */
    ItemStock selectByPrimaryKey(Integer id);

    ItemStock selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Dec 30 00:33:55 CST 2018
     */
    int updateByPrimaryKeySelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Dec 30 00:33:55 CST 2018
     */
    int updateByPrimaryKey(ItemStock record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);

}