package com.ccpd.forestsun.mapper;

import com.ccpd.forestsun.domain.SequenceInfo;

public interface SequenceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Jan 01 11:06:09 CST 2019
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Jan 01 11:06:09 CST 2019
     */
    int insert(SequenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Jan 01 11:06:09 CST 2019
     */
    int insertSelective(SequenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Jan 01 11:06:09 CST 2019
     */
    SequenceInfo selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Jan 01 11:06:09 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Jan 01 11:06:09 CST 2019
     */
    int updateByPrimaryKey(SequenceInfo record);

    SequenceInfo getSequenceByName(String name);
}